### ISSUE TITLE
config.yaml 设置正确的 device  序号 程序有错误输出

### ISSUE THREAD

**Issue by wuyafeiya** [h9-dev/spacemesh-miner#12]
![截屏2024-03-19 15 41 52](https://github.com/h9-dev/spacemesh-miner/assets/49944076/c5ffef41-b9d0-4de4-89be-b931924d8334)

config.yaml 配置中 extraParams:  中 device: 下 指定了正常的gpu序号,程序执行还是出现上图的错误

**Comment by trying2016** [comment]
设备启动的时候会打印设备信息，提示这个错误，应该是id不正常
