### ISSUE TITLE
Add support for offloading k2pow compute

### ISSUE THREAD

**Issue by felixbrucker** [h9-dev/spacemesh-miner#15]
Currently the local node computes the k2pow, which can be a problem for old low power cpu's. Proof reading compute is less of an issue.
A i3-4005U takes more than 40 minutes to compute k2pow for 4 SU, while a ryzen 5 5500U takes just a few seconds.

It would be helpful to offload the k2pow compute to other servers, similarly to how the gpu compute for plotting is offloaded to other servers via the gpuServer setting

**Comment by trying2016** [comment]
Version 4.0.0 already supports distributed computing
