### ISSUE TITLE
downgrade performance to 4.0.0-2

### ISSUE THREAD

**Issue by blasteffect** [h9-dev/spacemesh-miner#20]
Hi,

after updated the version 3.0.3-1 to 4.0.0-1, I see the loss of performance visible on the network reception curve during plotting.
All server is in 4.0.0-2 version
![Capture d’écran du 2024-06-30 18-38-33](https://github.com/h9-dev/spacemesh-miner/assets/38509444/5338b616-4ca8-4af8-ab53-f37e2218d457)
![Capture d’écran du 2024-06-30 18-36-33](https://github.com/h9-dev/spacemesh-miner/assets/38509444/aa923880-faac-4395-81cd-8462b3cb85e3)

**Comment by trying2016** [comment]
In order to improve plot performance, the amount of single calculation has increased compared to version 3.0, the single data transmission over the network is larger, and the interval between transmissions has increased compared to version 3.0.
