### ISSUE TITLE
不显示硬盘容量

### ISSUE THREAD

**Issue by ggshxjn** [h9-dev/spacemesh-miner#21]
今天突然发现新增的两块硬盘不显示硬盘容量，之前都是正常的，3.03版本升级到最新4.0版本也是一样。
尝试着P了5T左右，打开硬盘的话会看到一个文件夹占用所有容量，不显示硬盘容量。
![Uploading 111111111111.png…]()

**Comment by ggshxjn** [comment]
![111111111111](https://github.com/h9-dev/spacemesh-miner/assets/174642074/fa05633b-8fa6-409b-af9c-550b2af09587)

**Comment by ggshxjn** [comment]
硬盘也尝试重新删除分区重新格式化了 都不行。

**Comment by ggshxjn** [comment]
今天换了新的电脑 安装全新4.00（3）版本 新的硬盘 还是硬盘容量显示为0

**Comment by trying2016** [comment]
没Plot完成，不会显示容量信息。具体可以看启动日志
