### ISSUE TITLE
The source code and compilation project for libpost_cuda.so

### ISSUE THREAD

**Issue by Lacacy** [h9-dev/spacemesh-miner#22]
Could you please provide me with the source code for libpost_cuda.so? I am looking to adapt the compilation settings for use on an AMD GPU, leveraging AMD's HIP to achieve CUDA-like acceleration. My email address is [wkxtly@gmail.com](mailto:wkxtly@gmail.com). Your assistance would be greatly appreciated.

**Comment by Lacacy** [comment]
请问是否可以提供给我一份libpost_cuda.so的代码，我在amd的GPU想要基于AMD的HIP更改编译配置，利用AMD的GPU实现类似Cuda的加速，我的邮件地址：[wkxtly@gmail.com](mailto:wkxtly@gmail.com)

如果您能够提供，我将非常感谢。

**Comment by trying2016** [comment]
Plot can compile the https://github.com/ZakuroLab/post-rs library and replace libpost_cuda.so

**Comment by Lacacy** [comment]
你们依赖的 libpost.so 之中，包含 new_random_x 的函数名，我基于 
https://github.com/ZakuroLab/post-rs 编译后生成的 libpost.so, 不包含 new_random_x  的函数名，无法解决。
