### ISSUE TITLE
The source code of H9-Miner-spacemesh-v4.0.0-5-linux.zip

### ISSUE THREAD

**Issue by keens312** [h9-dev/spacemesh-miner#24]
H9开发团队，请问能否发我一下H9-Miner-spacemesh-v4.0.0-5-linux.zip的源码，用于排查启动时的错误。
在github源码中仅有README.md文件，请发keens312@hotmail.com

**Comment by trying2016** [comment]
有问题可以找我们的客服人员或者是提Issue寻求帮助
