### ISSUE TITLE
日志显示"Plot skip Uninitialized"，如何解决

### ISSUE THREAD

**Issue by keens312** [h9-dev/spacemesh-miner#26]
P盘日志如下
INFO[2024-07-30 08:11 40] Plot skip Uninitialized                       path=/mnt/sdc/h9/spacemesh
INFO[2024-07-30 08:11 40] upload status                                
INFO[2024-07-30 08:11 41] Plot skip Uninitialized                       path=/mnt/sdc/h9/spacemesh
INFO[2024-07-30 08:11 42] Plot skip Uninitialized                       path=/mnt/sdc/h9/spacemesh
INFO[2024-07-30 08:11 43] Plot skip Uninitialized                       path=/mnt/sdc/h9/spacemesh
INFO[2024-07-30 08:11 44] Plot skip Uninitialized                       path=/mnt/sdc/h9/spacemesh
INFO[2024-07-30 08:11 45] Plot skip Uninitialized                       path=/mnt/sdc/h9/spacemesh
INFO[2024-07-30 08:11 46] Plot skip Uninitialized                       path=/mnt/sdc/h9/spacemesh
INFO[2024-07-30 08:11 47] Plot skip Uninitialized                       path=/mnt/sdc/h9/spacemesh
INFO[2024-07-30 08:11 48] Plot skip Uninitialized                       path=/mnt/sdc/h9/spacemesh
INFO[2024-07-30 08:11 49] Plot skip Uninitialized                       path=/mnt/sdc/h9/spacemesh
INFO[2024-07-30 08:11 50] Plot skip Uninitialized                       path=/mnt/sdc/h9/spacemesh
INFO[2024-07-30 08:11 51] Plot skip Uninitialized                       path=/mnt/sdc/h9/spacemesh
这个频繁打印，含义是什么，需要解决还是忽略它

**Comment by trying2016** [comment]
这个是因为开启了skipUninitialized，有文件为完成initialize
可以在配置文件中skipUninitialized设置为false，就不会管是否完成了初始化
