### ISSUE TITLE
扫盘日志出现很多level=error msg="Failed to get PoST challenge, wait 30s and try again" error="request timed out" 是什么问题?如何处理

### ISSUE THREAD

**Issue by yuqi33** [h9-dev/spacemesh-miner#28]
time="2024-08-06 08:10 02" level=error msg="Failed to get PoST challenge, wait 30s and try again" error="request timed out" f7="{loggers.go,logging.CPrint,168}" f8="{nzE1Rdw2.go,kQ8REFYN.(*MCA92AnW).kPOMG3lq,1}" f9="{DQxCyG6c.go,kQ8REFYN.(*MCA92AnW).kvCvTj88,1}" nodeId=d92cfb92d09d58d8de49f559148e5647e4a6860bc3882be5969fba63a5753c4e retry=2/3
time="2024-08-06 08:10 12" level=error msg="Failed to get PoST challenge, wait 30s and try again" error="request timed out" f7="{loggers.go,logging.CPrint,168}" f8="{nzE1Rdw2.go,kQ8REFYN.(*MCA92AnW).kPOMG3lq,1}" f9="{DQxCyG6c.go,kQ8REFYN.(*MCA92AnW).kvCvTj88,1}" nodeId=b6c2f55c1b2ef23f89b8ebc2b47037a50a7dd1921216a0470998b39358a413d2 retry=3/3
time="2024-08-06 08:10 22" level=error msg="Failed to get PoST challenge, wait 30s and try again" error="request timed out" f7="{loggers.go,logging.CPrint,168}" f8="{nzE1Rdw2.go,kQ8REFYN.(*MCA92AnW).kPOMG3lq,1}" f9="{DQxCyG6c.go,kQ8REFYN.(*MCA92AnW).kvCvTj88,1}" nodeId=436f06cd691a36ddd56c9fbc6593305751d66f68bc22c2b7015e372d1c1457ac retry=3/3
time="2024-08-06 08:10 32" level=error msg="Failed to get PoST challenge, wait 30s and try again" error="request timed out" f7="{loggers.go,logging.CPrint,168}" f8="{nzE1Rdw2.go,kQ8REFYN.(*MCA92AnW).kPOMG3lq,1}" f9="{DQxCyG6c.go,kQ8REFYN.(*MCA92AnW).kvCvTj88,1}" nodeId=27c396e1f5ab9006ece7328c010a0dcc7a16db3fbfd1babc4d8b7e23aa569e8a retry=3/3
time="2024-08-06 08:10 42" level=error msg="requestProof: getPoSTChallenge failed" error="get challenge failed" f7="{loggers.go,logging.CPrint,168}" f8="{GIMZzLDj.go,kQ8REFYN.(*MCA92AnW).zSx45GSd,1}" f9="{CVakA6oE.go,kQ8REFYN.(*MCA92AnW).msbsj4Km.func27,1}" nodeId=b6c2f55c1b2ef23f89b8ebc2b47037a50a7dd1921216a0470998b39358a413d2
time="2024-08-06 08:10 42" level=error msg="Failed to get PoST challenge, wait 30s and try again" error="request timed out" f7="{loggers.go,logging.CPrint,168}" f8="{nzE1Rdw2.go,kQ8REFYN.(*MCA92AnW).kPOMG3lq,1}" f9="{DQxCyG6c.go,kQ8REFYN.(*MCA92AnW).kvCvTj88,1}" nodeId=18861038f467411aed633774572bfefa7ff06d3c8670d55c57f0f8ed6bf8ce8c retry=3/3
time="2024-08-06 08:10 52" level=error msg="requestProof: getPoSTChallenge failed" error="get challenge failed" f7="{loggers.go,logging.CPrint,168}" f8="{GIMZzLDj.go,kQ8REFYN.(*MCA92AnW).zSx45GSd,1}" f9="{CVakA6oE.go,kQ8REFYN.(*MCA92AnW).msbsj4Km.func27,1}" nodeId=436f06cd691a36ddd56c9fbc6593305751d66f68bc22c2b7015e372d1c1457ac
time="2024-08-06 08:10 52" level=error msg="Failed to get PoST challenge, wait 30s and try again" error="request timed out" f7="{loggers.go,logging.CPrint,168}" f8="{nzE1Rdw2.go,kQ8REFYN.(*MCA92AnW).kPOMG3lq,1}" f9="{DQxCyG6c.go,kQ8REFYN.(*MCA92AnW).kvCvTj88,1}" nodeId=28e4f150c0d36975dcfdf7fa9a156bd8a3b0499d2ff0ac3c462f276054f9e69c retry=3/3
time="2024-08-06 08:11 02" level=error msg="requestProof: getPoSTChallenge failed" error="get challenge failed" f7="{loggers.go,logging.CPrint,168}" f8="{GIMZzLDj.go,kQ8REFYN.(*MCA92AnW).zSx45GSd,1}" f9="{CVakA6oE.go,kQ8REFYN.(*MCA92AnW).msbsj4Km.func27,1}" nodeId=27c396e1f5ab9006ece7328c010a0dcc7a16db3fbfd1babc4d8b7e23aa569e8a
time="2024-08-06 08:11 02" level=error msg="Failed to get PoST challenge, wait 30s and try again" error="request timed out" f7="{loggers.go,logging.CPrint,168}" f8="{nzE1Rdw2.go,kQ8REFYN.(*MCA92AnW).kPOMG3lq,1}" f9="{DQxCyG6c.go,kQ8REFYN.(*MCA92AnW).kvCvTj88,1}" nodeId=759460a73cfb78be1b3c43e52fe1619cb6427fee05e2dbddf103e96b0ba9df40 retry=3/3

**Comment by trying2016** [comment]
检查和服务器连接是否正常，有用x-proxy的话，也要看下x-proxy的日志是不是连接服务器失败。

**Comment by yuqi33** [comment]
> 检查和服务器连接是否正常，有用x-proxy的话，也要看下x-proxy的日志是不是连接服务器失败。

服务器和 x-proxy 之间网络正常,,x-proxy也没有异常日志,,

~# ping -c 10000 -f 172.16.101.45
PING 172.16.101.45 (172.16.101.45) 56(84) bytes of data.

--- 172.16.101.45 ping statistics ---
10000 packets transmitted, 10000 received, 0% packet loss, time 119001ms
rtt min/avg/max/mdev = 35.693/35.834/36.432/0.050 ms, pipe 4, ipg/ewma 11.901/35.833 ms


服务器 error 日志:
time="2024-08-06 09:55 20" level=error msg="Submit post failed, wait 10s and try again" error="request timed out" f7="{loggers.go,logging.CPrint,168}" f8="{l6SwKRjj.go,kQ8REFYN.(*MCA92AnW).u1pT4lna,1}" f9="{queue.go,utils.(*Queue).run,55}" nodeId=a4b6d1da830ec107622859bad0d15f9400cb0ac2e93dbc9361b1dc91abf345da success=2 total=72
time="2024-08-06 09:55 21" level=info msg="new mining info" capacity="64.50 TiB" chain=SpaceMesh difficulty=5448114957008440576 height=111959 jobId=568 scan consume=0 scan time="2024-08-06 09:55:21"
time="2024-08-06 09:55 24" level=error msg="Failed to get PoST challenge, wait 30s and try again" error="request timed out" f7="{loggers.go,logging.CPrint,168}" f8="{nzE1Rdw2.go,kQ8REFYN.(*MCA92AnW).kPOMG3lq,1}" f9="{DQxCyG6c.go,kQ8REFYN.(*MCA92AnW).kvCvTj88,1}" nodeId=b3d1842b193f038d035bf8bcbff330c6d77ba17cf916a0cb187a1ba5e31fa965 retry=3/3
time="2024-08-06 09:55 34" level=error msg="Failed to get PoST challenge, wait 30s and try again" error="request timed out" f7="{loggers.go,logging.CPrint,168}" f8="{nzE1Rdw2.go,kQ8REFYN.(*MCA92AnW).kPOMG3lq,1}" f9="{DQxCyG6c.go,kQ8REFYN.(*MCA92AnW).kvCvTj88,1}" nodeId=78283fa9e1c161b4a186b25669ebcd859eb8e98cc273e564325265cfc67bfa9e retry=2/3
time="2024-08-06 09:55 40" level=error msg="Submit post failed, wait 10s and try again" error="request timed out" f7="{loggers.go,logging.CPrint,168}" f8="{l6SwKRjj.go,kQ8REFYN.(*MCA92AnW).u1pT4lna,1}" f9="{queue.go,utils.(*Queue).run,55}" nodeId=a4b6d1da830ec107622859bad0d15f9400cb0ac2e93dbc9361b1dc91abf345da success=2 total=72
time="2024-08-06 09:55 44" level=error msg="requestProof: getPoSTChallenge failed" error="get challenge failed" f7="{loggers.go,logging.CPrint,168}" f8="{GIMZzLDj.go,kQ8REFYN.(*MCA92AnW).zSx45GSd,1}" f9="{CVakA6oE.go,kQ8REFYN.(*MCA92AnW).msbsj4Km.func27,1}" nodeId=79027afba1021f013983730fcebe7ba46a8f8b99294eca05d7d640bdf83cedc6
time="2024-08-06 09:55 44" level=error msg="Failed to get PoST challenge, wait 30s and try again" error="request timed out" f7="{loggers.go,logging.CPrint,168}" f8="{nzE1Rdw2.go,kQ8REFYN.(*MCA92AnW).kPOMG3lq,1}" f9="{DQxCyG6c.go,kQ8REFYN.(*MCA92AnW).kvCvTj88,1}" nodeId=9af2737fdb9f397bc74e9282064e0841b52cbd51c4a965734406b96da11646ac retry=3/3
time="2024-08-06 09:55 54" level=error msg="requestProof: getPoSTChallenge failed" error="get challenge failed" f7="{loggers.go,logging.CPrint,168}" f8="{GIMZzLDj.go,kQ8REFYN.(*MCA92AnW).zSx45GSd,1}" f9="{CVakA6oE.go,kQ8REFYN.(*MCA92AnW).msbsj4Km.func27,1}" nodeId=b3d1842b193f038d035bf8bcbff330c6d77ba17cf916a0cb187a1ba5e31fa965
time="2024-08-06 09:55 54" level=error msg="Failed to get PoST challenge, wait 30s and try again" error="request timed out" f7="{loggers.go,logging.CPrint,168}" f8="{nzE1Rdw2.go,kQ8REFYN.(*MCA92AnW).kPOMG3lq,1}" f9="{DQxCyG6c.go,kQ8REFYN.(*MCA92AnW).kvCvTj88,1}" nodeId=8de979d8eb311092b7a49f1172649bca2ab6beaf7977c70bc2c9f3cb17a4b45a retry=2/3
time="2024-08-06 09:55 54" level=info msg="Found proof for nonce: 1525, pow: 190519 with [881757425, 1352564547, 1354527623, 6454104094, 8397114603, 9015372160, 11223883006, 11425498243, 11761008207, 12254905596, 12567452302, 12902811233, 18525713617, 19866105053, 21311322975, 21618557689, 22038671405, 23499142075, 23586412621, 24498865749, 25166962564, 26087305849, 27520917411, 31614875306, 35975947496, 36041648995, 37343360749, 38103874674, 38834471232, 42364379212, 44454720609, 47062210893, 47942019757, 49474406405, 49834579499, 51060635012, 56538074827] indices" file=src/prove.rs line=486 module="post::prove"
time="2024-08-06 09:56 00" level=error msg="Submit post failed, wait 10s and try again" error="request timed out" f7="{loggers.go,logging.CPrint,168}" f8="{l6SwKRjj.go,kQ8REFYN.(*MCA92AnW).u1pT4lna,1}" f9="{queue.go,utils.(*Queue).run,55}" nodeId=a4b6d1da830ec107622859bad0d15f9400cb0ac2e93dbc9361b1dc91abf345da success=2 total=72
time="2024-08-06 09:56 04" level=error msg="Failed to get PoST challenge, wait 30s and try again" error="request timed out" f7="{loggers.go,logging.CPrint,168}" f8="{nzE1Rdw2.go,kQ8REFYN.(*MCA92AnW).kPOMG3lq,1}" f9="{DQxCyG6c.go,kQ8REFYN.(*MCA92AnW).kvCvTj88,1}" nodeId=40938ede79ffc38833f8979518fa0083d7341cf46c064a6b83f34eb6172a8498 retry=3/3
time="2024-08-06 09:56 14" level=error msg="Failed to get PoST challenge, wait 30s and try again" error="request timed out" f7="{loggers.go,logging.CPrint,168}" f8="{nzE1Rdw2.go,kQ8REFYN.(*MCA92AnW).kPOMG3lq,1}" f9="{DQxCyG6c.go,kQ8REFYN.(*MCA92AnW).kvCvTj88,1}" nodeId=baa86b14eea64596767f364baeece76e81b431f9b5dadf17853097f3975c87e3 retry=1/3
time="2024-08-06 09:56 14" level=error msg="requestProof: getPoSTChallenge failed" error="get challenge failed" f7="{loggers.go,logging.CPrint,168}" f8="{GIMZzLDj.go,kQ8REFYN.(*MCA92AnW).zSx45GSd,1}" f9="{CVakA6oE.go,kQ8REFYN.(*MCA92AnW).msbsj4Km.func27,1}" nodeId=9af2737fdb9f397bc74e9282064e0841b52cbd51c4a965734406b96da11646ac
time="2024-08-06 09:56 17" level=info msg="upload status"
time="2024-08-06 09:56 20" level=error msg="Submit post failed, wait 10s and try again" error="request timed out" f7="{loggers.go,logging.CPrint,168}" f8="{l6SwKRjj.go,kQ8REFYN.(*MCA92AnW).u1pT4lna,1}" f9="{queue.go,utils.(*Queue).run,55}" nodeId=a4b6d1da830ec107622859bad0d15f9400cb0ac2e93dbc9361b1dc91abf345da success=2 total=72
time="2024-08-06 09:56 24" level=error msg="Failed to get PoST challenge, wait 30s and try again" error="request timed out" f7="{loggers.go,logging.CPrint,168}" f8="{nzE1Rdw2.go,kQ8REFYN.(*MCA92AnW).kPOMG3lq,1}" f9="{DQxCyG6c.go,kQ8REFYN.(*MCA92AnW).kvCvTj88,1}" nodeId=650e7a67d9f006bb142b9a46c2525285dc98ed814261399379e2e80468ae333c retry=3/3
time="2024-08-06 09:56 34" level=error msg="requestProof: getPoSTChallenge failed" error="get challenge failed" f7="{loggers.go,logging.CPrint,168}" f8="{GIMZzLDj.go,kQ8REFYN.(*MCA92AnW).zSx45GSd,1}" f9="{CVakA6oE.go,kQ8REFYN.(*MCA92AnW).msbsj4Km.func27,1}" nodeId=40938ede79ffc38833f8979518fa0083d7341cf46c064a6b83f34eb6172a8498
time="2024-08-06 09:56 34" level=error msg="Failed to get PoST challenge, wait 30s and try again" error="request timed out" f7="{loggers.go,logging.CPrint,168}" f8="{nzE1Rdw2.go,kQ8REFYN.(*MCA92AnW).kPOMG3lq,1}" f9="{DQxCyG6c.go,kQ8REFYN.(*MCA92AnW).kvCvTj88,1}" nodeId=1bb13ec9da0c41a147cd8427f0e43dd97ec57b7ceea4e888a7a42a772bfaf11e retry=3/3
time="2024-08-06 09:56 40" level=error msg="Submit post failed, wait 10s and try again" error="request timed out" f7="{loggers.go,logging.CPrint,168}" f8="{l6SwKRjj.go,kQ8REFYN.(*MCA92AnW).u1pT4lna,1}" f9="{queue.go,utils.(*Queue).run,55}" nodeId=a4b6d1da830ec107622859bad0d15f9400cb0ac2e93dbc9361b1dc91abf345da success=2 total=72
time="2024-08-06 09:56 44" level=error msg="Failed to get PoST challenge, wait 30s and try again" error="request timed out" f7="{loggers.go,logging.CPrint,168}" f8="{nzE1Rdw2.go,kQ8REFYN.(*MCA92AnW).kPOMG3lq,1}" f9="{DQxCyG6c.go,kQ8REFYN.(*MCA92AnW).kvCvTj88,1}" nodeId=597649ffebda2ac09d9f2bb8d977d2a77b5a2b34f8299b869635b811c4bd5df4 retry=2/3
time="2024-08-06 09:56 54" level=error msg="requestProof: getPoSTChallenge failed" error="get challenge failed" f7="{loggers.go,logging.CPrint,168}" f8="{GIMZzLDj.go,kQ8REFYN.(*MCA92AnW).zSx45GSd,1}" f9="{CVakA6oE.go,kQ8REFYN.(*MCA92AnW).msbsj4Km.func27,1}" nodeId=650e7a67d9f006bb142b9a46c2525285dc98ed814261399379e2e80468ae333c
time="2024-08-06 09:56 54" level=error msg="Failed to get PoST challenge, wait 30s and try again" error="request timed out" f7="{loggers.go,logging.CPrint,168}" f8="{nzE1Rdw2.go,kQ8REFYN.(*MCA92AnW).kPOMG3lq,1}" f9="{DQxCyG6c.go,kQ8REFYN.(*MCA92AnW).kvCvTj88,1}" nodeId=0c4e639663df7c8a714d63df997c047a6b59b16bdceca578a0b8fe995a7cfee2 retry=1/3
time="2024-08-06 09:57 00" level=error msg="Submit post failed, wait 10s and try again" error="request timed out" f7="{loggers.go,logging.CPrint,168}" f8="{l6SwKRjj.go,kQ8REFYN.(*MCA92AnW).u1pT4lna,1}" f9="{queue.go,utils.(*Queue).run,55}" nodeId=a4b6d1da830ec107622859bad0d15f9400cb0ac2e93dbc9361b1dc91abf345da success=2 total=72
time="2024-08-06 09:57 04" level=error msg="requestProof: getPoSTChallenge failed" error="get challenge failed" f7="{loggers.go,logging.CPrint,168}" f8="{GIMZzLDj.go,kQ8REFYN.(*MCA92AnW).zSx45GSd,1}" f9="{CVakA6oE.go,kQ8REFYN.(*MCA92AnW).msbsj4Km.func27,1}" nodeId=1bb13ec9da0c41a147cd8427f0e43dd97ec57b7ceea4e888a7a42a772bfaf11e
time="2024-08-06 09:57 04" level=error msg="Failed to get PoST challenge, wait 30s and try again" error="request timed out" f7="{loggers.go,logging.CPrint,168}" f8="{nzE1Rdw2.go,kQ8REFYN.(*MCA92AnW).kPOMG3lq,1}" f9="{DQxCyG6c.go,kQ8REFYN.(*MCA92AnW).kvCvTj88,1}" nodeId=7b86fefdb67719846634ea9f8628b822b365886ff1b74eb80be4b16a0241d306 retry=1/3
time="2024-08-06 09:57 14" level=error msg="Failed to get PoST challenge, wait 30s and try again" error="request timed out" f7="{loggers.go,logging.CPrint,168}" f8="{nzE1Rdw2.go,kQ8REFYN.(*MCA92AnW).kPOMG3lq,1}" f9="{DQxCyG6c.go,kQ8REFYN.(*MCA92AnW).kvCvTj88,1}" nodeId=78283fa9e1c161b4a186b25669ebcd859eb8e98cc273e564325265cfc67bfa9e retry=3/3
time="2024-08-06 09:57 20" level=error msg="Submit post failed, wait 10s and try again" error="request timed out" f7="{loggers.go,logging.CPrint,168}" f8="{l6SwKRjj.go,kQ8REFYN.(*MCA92AnW).u1pT4lna,1}" f9="{queue.go,utils.(*Queue).run,55}" nodeId=a4b6d1da830ec107622859bad0d15f9400cb0ac2e93dbc9361b1dc91abf345da success=2 total=72
time="2024-08-06 09:57 24" level=error msg="Failed to get PoST challenge, wait 30s and try again" error="request timed out" f7="{loggers.go,logging.CPrint,168}" f8="{nzE1Rdw2.go,kQ8REFYN.(*MCA92AnW).kPOMG3lq,1}" f9="{DQxCyG6c.go,kQ8REFYN.(*MCA92AnW).kvCvTj88,1}" nodeId=c46850d5460cdc688b5b5b8617e8f82b78d661903f8ddc94c58258c53b4cdd4e retry=1/3
time="2024-08-06 09:57 34" level=error msg="Failed to get PoST challenge, wait 30s and try again" error="request timed out" f7="{loggers.go,logging.CPrint,168}" f8="{nzE1Rdw2.go,kQ8REFYN.(*MCA92AnW).kPOMG3lq,1}" f9="{DQxCyG6c.go,kQ8REFYN.(*MCA92AnW).kvCvTj88,1}" nodeId=e225221a313cb1b11a001597b9060f33f3b4550d2c2ada3d9a28c875fc104680 retry=1/3
time="2024-08-06 09:57 40" level=error msg="Submit post failed, wait 10s and try again" error="request timed out" f7="{loggers.go,logging.CPrint,168}" f8="{l6SwKRjj.go,kQ8REFYN.(*MCA92AnW).u1pT4lna,1}" f9="{queue.go,utils.(*Queue).run,55}" nodeId=a4b6d1da830ec107622859bad0d15f9400cb0ac2e93dbc9361b1dc91abf345da success=2 total=72
time="2024-08-06 09:57 44" level=error msg="requestProof: getPoSTChallenge failed" error="get challenge failed" f7="{loggers.go,logging.CPrint,168}" f8="{GIMZzLDj.go,kQ8REFYN.(*MCA92AnW).zSx45GSd,1}" f9="{CVakA6oE.go,kQ8REFYN.(*MCA92AnW).msbsj4Km.func27,1}" nodeId=78283fa9e1c161b4a186b25669ebcd859eb8e98cc273e564325265cfc67bfa9e
time="2024-08-06 09:57 44" level=error msg="Failed to get PoST challenge, wait 30s and try again" error="request timed out" f7="{loggers.go,logging.CPrint,168}" f8="{nzE1Rdw2.go,kQ8REFYN.(*MCA92AnW).kPOMG3lq,1}" f9="{DQxCyG6c.go,kQ8REFYN.(*MCA92AnW).kvCvTj88,1}" nodeId=8de979d8eb311092b7a49f1172649bca2ab6beaf7977c70bc2c9f3cb17a4b45a retry=3/3

x-proxy 日志
2024/08/06 09:30:00 [I] new mining info, chain: Spacemesh height: 111954 jobId: 563 enable:true
2024/08/06 09:30:15 [I] total client count:201 need close count:0
2024/08/06 09:31:15 [I] total client count:201 need close count:0
2024/08/06 09:32:15 [I] total client count:201 need close count:0
2024/08/06 09:33:15 [I] total client count:201 need close count:0
2024/08/06 09:34:15 [I] total client count:201 need close count:0
2024/08/06 09:35:01 [I] new mining info, chain: Spacemesh height: 111955 jobId: 564 enable:true
2024/08/06 09:35:15 [I] total client count:201 need close count:0
2024/08/06 09:36:15 [I] total client count:201 need close count:0
2024/08/06 09:37:15 [I] total client count:201 need close count:0
2024/08/06 09:38:15 [I] total client count:201 need close count:0
2024/08/06 09:39:15 [I] total client count:201 need close count:0
2024/08/06 09:40:01 [I] new mining info, chain: Spacemesh height: 111956 jobId: 565 enable:true
2024/08/06 09:40:15 [I] total client count:201 need close count:0
2024/08/06 09:41:15 [I] total client count:201 need close count:0
2024/08/06 09:42:15 [I] total client count:201 need close count:0
2024/08/06 09:43:15 [I] total client count:201 need close count:0
2024/08/06 09:44:15 [I] total client count:201 need close count:0
2024/08/06 09:45:00 [I] new mining info, chain: Spacemesh height: 111957 jobId: 566 enable:true
2024/08/06 09:45:15 [I] total client count:201 need close count:0
2024/08/06 09:46:15 [I] total client count:201 need close count:0
2024/08/06 09:47:15 [I] total client count:201 need close count:0
2024/08/06 09:48:15 [I] total client count:201 need close count:0
2024/08/06 09:49:15 [I] total client count:201 need close count:0
2024/08/06 09:50:01 [I] new mining info, chain: Spacemesh height: 111958 jobId: 567 enable:true
2024/08/06 09:50:15 [I] total client count:201 need close count:0
2024/08/06 09:51:15 [I] total client count:201 need close count:0
2024/08/06 09:52:15 [I] total client count:201 need close count:0
2024/08/06 09:53:15 [I] total client count:201 need close count:0
2024/08/06 09:54:15 [I] total client count:201 need close count:0
2024/08/06 09:55:00 [I] new mining info, chain: Spacemesh height: 111959 jobId: 568 enable:true
2024/08/06 09:55:15 [I] total client count:201 need close count:0
2024/08/06 09:56:15 [I] total client count:201 need close count:0

**Comment by yuqi33** [comment]
另外一台 x-proxy可以代理多少服务器,有数量限制吗?

**Comment by trying2016** [comment]
拆分为2个x-proxy试试。

**Comment by yuqi33** [comment]
1个 x-proxy 挂太多服务器确实有问题,,扫盘的时候不稳定,服务器循环出现离线..现在拆成了两个 x-proxy,,没再出现离线服务器了,但还是有 error 的情况,,

**Comment by trying2016** [comment]
要看具体报什么error

**Comment by yuqi33** [comment]
> 要看具体报什么error

还是报这种level=error msg="Failed to get PoST challenge, wait 30s and try again" error="request timed out"


dell128 | CHANGED | rc=0 >>
time="2024-08-06 14:37 00" level=error msg="Failed to get PoST challenge, wait 30s and try again" error="request timed out" f7="{loggers.go,logging.CPrint,168}" f8="{nzE1Rdw2.go,kQ8REFYN.(*MCA92AnW).kPOMG3lq,1}" f9="{DQxCyG6c.go,kQ8REFYN.(*MCA92AnW).kvCvTj88,1}" nodeId=2a5364ea732645430b36e9ce3b8c83a51835407d86fe58a3643ba5046b8426cc retry=3/3
time="2024-08-06 14:37 10" level=error msg="Failed to get PoST challenge, wait 30s and try again" error="request timed out" f7="{loggers.go,logging.CPrint,168}" f8="{nzE1Rdw2.go,kQ8REFYN.(*MCA92AnW).kPOMG3lq,1}" f9="{DQxCyG6c.go,kQ8REFYN.(*MCA92AnW).kvCvTj88,1}" nodeId=7eacadc1df6d4f7d1d5fd426bdf2c354de7d947c87acd4e983b155a139951783 retry=1/3
time="2024-08-06 14:37 14" level=error msg="Submit post failed, wait 10s and try again" error="request timed out" f7="{loggers.go,logging.CPrint,168}" f8="{l6SwKRjj.go,kQ8REFYN.(*MCA92AnW).u1pT4lna,1}" f9="{queue.go,utils.(*Queue).run,55}" nodeId=2beb420c0f81b81d79564a7a93c71e94d991be54249ae01494cd0dc194c9e5c7 success=1 total=72
dell129 | CHANGED | rc=0 >>
time="2024-08-06 14:37 04" level=error msg="Failed to get PoST challenge, wait 30s and try again" error="request timed out" f7="{loggers.go,logging.CPrint,168}" f8="{nzE1Rdw2.go,kQ8REFYN.(*MCA92AnW).kPOMG3lq,1}" f9="{DQxCyG6c.go,kQ8REFYN.(*MCA92AnW).kvCvTj88,1}" nodeId=8653276efe23ac61b7c08997df03b858b90f63de4cadef5285a5f2130cec6705 retry=2/3
time="2024-08-06 14:37 14" level=error msg="requestProof: getPoSTChallenge failed" error="get challenge failed" f7="{loggers.go,logging.CPrint,168}" f8="{GIMZzLDj.go,kQ8REFYN.(*MCA92AnW).zSx45GSd,1}" f9="{CVakA6oE.go,kQ8REFYN.(*MCA92AnW).msbsj4Km.func27,1}" nodeId=67cc8e2e723e104f9615faaa074979e4c53bc73b2eec1a287e8bdc12def3ec2c
time="2024-08-06 14:37 14" level=error msg="Failed to get PoST challenge, wait 30s and try again" error="request timed out" f7="{loggers.go,logging.CPrint,168}" f8="{nzE1Rdw2.go,kQ8REFYN.(*MCA92AnW).kPOMG3lq,1}" f9="{DQxCyG6c.go,kQ8REFYN.(*MCA92AnW).kvCvTj88,1}" nodeId=52e370ece623d7e999d1f27ac002f5a72ae8f8b0193b3ee6fb203aca0d72a308 retry=2/3
dell130 | CHANGED | rc=0 >>
time="2024-08-06 14:36 55" level=error msg="Failed to get PoST challenge, wait 30s and try again" error="request timed out" f7="{loggers.go,logging.CPrint,168}" f8="{nzE1Rdw2.go,kQ8REFYN.(*MCA92AnW).kPOMG3lq,1}" f9="{DQxCyG6c.go,kQ8REFYN.(*MCA92AnW).kvCvTj88,1}" nodeId=fc6d1654dbe01bec307cee8552d1c99efd43911559a679aa9cfab2d9b42279c2 retry=2/3
time="2024-08-06 14:37 05" level=error msg="Failed to get PoST challenge, wait 30s and try again" error="request timed out" f7="{loggers.go,logging.CPrint,168}" f8="{nzE1Rdw2.go,kQ8REFYN.(*MCA92AnW).kPOMG3lq,1}" f9="{DQxCyG6c.go,kQ8REFYN.(*MCA92AnW).kvCvTj88,1}" nodeId=dc243e48c08464f1845472635a9279c768a45a27623df52fc3bcdaf27ffa5b46 retry=1/3
time="2024-08-06 14:37 08" level=error msg="Submit post failed, wait 10s and try again" error="request timed out" f7="{loggers.go,logging.CPrint,168}" f8="{l6SwKRjj.go,kQ8REFYN.(*MCA92AnW).u1pT4lna,1}" f9="{queue.go,utils.(*Queue).run,55}" nodeId=c350facb5d5a700edd92593238e73402278448ea612c5fe937d602dc0684badf success=15 total=72
dell132 | CHANGED | rc=0 >>
time="2024-08-06 14:37 08" level=error msg="Failed to get PoST challenge, wait 30s and try again" error="request timed out" f7="{loggers.go,logging.CPrint,168}" f8="{nzE1Rdw2.go,kQ8REFYN.(*MCA92AnW).kPOMG3lq,1}" f9="{DQxCyG6c.go,kQ8REFYN.(*MCA92AnW).kvCvTj88,1}" nodeId=9e44f7df02d6cef7085ff0ae9605c52f62885f59bc850484612d18f33cc4ec26 retry=1/3
time="2024-08-06 14:37 18" level=error msg="requestProof: getPoSTChallenge failed" error="get challenge failed" f7="{loggers.go,logging.CPrint,168}" f8="{GIMZzLDj.go,kQ8REFYN.(*MCA92AnW).zSx45GSd,1}" f9="{CVakA6oE.go,kQ8REFYN.(*MCA92AnW).msbsj4Km.func27,1}" nodeId=728bff7622edc02dcca9d782ad1e41fa52a51a8fd59a108910005592fd348776
time="2024-08-06 14:37 18" level=error msg="Failed to get PoST challenge, wait 30s and try again" error="request timed out" f7="{loggers.go,logging.CPrint,168}" f8="{nzE1Rdw2.go,kQ8REFYN.(*MCA92AnW).kPOMG3lq,1}" f9="{DQxCyG6c.go,kQ8REFYN.(*MCA92AnW).kvCvTj88,1}" nodeId=687bd933a1f441289b02f2b3000dc4a0c3dea76da8fc23edb92ea23ed20adf12 retry=2/3
dell131 | CHANGED | rc=0 >>
time="2024-08-06 14:37 03" level=error msg="Failed to get PoST challenge, wait 30s and try again" error="request timed out" f7="{loggers.go,logging.CPrint,168}" f8="{nzE1Rdw2.go,kQ8REFYN.(*MCA92AnW).kPOMG3lq,1}" f9="{DQxCyG6c.go,kQ8REFYN.(*MCA92AnW).kvCvTj88,1}" nodeId=f9a1bbced6356e76b0b04c2cb53887910dc1deb755c2a8ea44ace925cfd6e479 retry=2/3
time="2024-08-06 14:37 08" level=error msg="Submit post failed, wait 10s and try again" error="request timed out" f7="{loggers.go,logging.CPrint,168}" f8="{l6SwKRjj.go,kQ8REFYN.(*MCA92AnW).u1pT4lna,1}" f9="{queue.go,utils.(*Queue).run,55}" nodeId=c8923228c2e899b59c1f70bbc4f60e36112cfa4b6d16f64f668839ffb8d04bab success=0 total=72
time="2024-08-06 14:37 13" level=error msg="Failed to get PoST challenge, wait 30s and try again" error="request timed out" f7="{loggers.go,logging.CPrint,168}" f8="{nzE1Rdw2.go,kQ8REFYN.(*MCA92AnW).kPOMG3lq,1}" f9="{DQxCyG6c.go,kQ8REFYN.(*MCA92AnW).kvCvTj88,1}" nodeId=72608576e60019cdcee9bc61c2b33f7be90d5ccf89affb691a2428abf1774eff retry=1/3
dell133 | CHANGED | rc=0 >>
time="2024-08-06 14:37 00" level=error msg="Submit post failed, wait 10s and try again" error="request timed out" f7="{loggers.go,logging.CPrint,168}" f8="{l6SwKRjj.go,kQ8REFYN.(*MCA92AnW).u1pT4lna,1}" f9="{queue.go,utils.(*Queue).run,55}" nodeId=66990fcc63074279b9eeaca1741bbef001620153d68ee673038aab11166864d0 success=21 total=72
time="2024-08-06 14:37 03" level=error msg="Failed to get PoST challenge, wait 30s and try again" error="request timed out" f7="{loggers.go,logging.CPrint,168}" f8="{nzE1Rdw2.go,kQ8REFYN.(*MCA92AnW).kPOMG3lq,1}" f9="{DQxCyG6c.go,kQ8REFYN.(*MCA92AnW).kvCvTj88,1}" nodeId=e1e879a8a0fac952c982d682682524bf4b6d0042a9168dbf3365005bb7df6fb9 retry=2/3
time="2024-08-06 14:37 13" level=error msg="Failed to get PoST challenge, wait 30s and try again" error="request timed out" f7="{loggers.go,logging.CPrint,168}" f8="{nzE1Rdw2.go,kQ8REFYN.(*MCA92AnW).kPOMG3lq,1}" f9="{DQxCyG6c.go,kQ8REFYN.(*MCA92AnW).kvCvTj88,1}" nodeId=f084461fc64b9821875283f70be2f8e3534bf446e5cbd8b67c0cdff20cc97bba retry=1/3

**Comment by trying2016** [comment]
x-proxy的机器配置不行吗？

**Comment by trying2016** [comment]
再拆几个x-proxy吧

**Comment by yuqi33** [comment]
> x-proxy的机器配置不行吗？


x-proxy 开的虚机,配置一般,,x-proxy 对服务器配置什么要求?

**Comment by trying2016** [comment]
最好是m.2的硬盘，cpu尽量好些

**Comment by trying2016** [comment]
虚拟机性能太差，直接跑物理机上。
也可以在现在的miner机器上开x-proxy跑。

**Comment by yuqi33** [comment]
一般一个 x-proxy挂多少台服务器比较合适?

**Comment by trying2016** [comment]
和你自己机器的配置有关系。

**Comment by yuqi33** [comment]
看 x-proxy 的资源占用情况并不是很厉害呀,之前挂300个 miner 一直很稳定的,,现在miner增加到400就开始出问题,, 增加了一台 x-proxy 分出去200台 miner 还是有问题

**Comment by trying2016** [comment]
找物理机开x-proxy吧

**Comment by yuqi33** [comment]
> 找物理机开x-proxy吧

找到问题了,应该是 x-proxy 到矿池之间的网络丢包导致,,,调整网络以后一台虚机开 x-proxy带400台 miner 也很稳定.
